/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PanierMystereService } from "../panierMystere.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PanierMystereCreateInput } from "./PanierMystereCreateInput";
import { PanierMystere } from "./PanierMystere";
import { PanierMystereFindManyArgs } from "./PanierMystereFindManyArgs";
import { PanierMystereWhereUniqueInput } from "./PanierMystereWhereUniqueInput";
import { PanierMystereUpdateInput } from "./PanierMystereUpdateInput";
import { FavorisFindManyArgs } from "../../favoris/base/FavorisFindManyArgs";
import { Favoris } from "../../favoris/base/Favoris";
import { FavorisWhereUniqueInput } from "../../favoris/base/FavorisWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PanierMystereControllerBase {
  constructor(
    protected readonly service: PanierMystereService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PanierMystere })
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPanierMystere(
    @common.Body() data: PanierMystereCreateInput
  ): Promise<PanierMystere> {
    return await this.service.createPanierMystere({
      data: {
        ...data,

        restaurant: data.restaurant
          ? {
              connect: data.restaurant,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        nom: true,
        prix: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PanierMystere] })
  @ApiNestedQuery(PanierMystereFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async panierMysteres(
    @common.Req() request: Request
  ): Promise<PanierMystere[]> {
    const args = plainToClass(PanierMystereFindManyArgs, request.query);
    return this.service.panierMysteres({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        nom: true,
        prix: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PanierMystere })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async panierMystere(
    @common.Param() params: PanierMystereWhereUniqueInput
  ): Promise<PanierMystere | null> {
    const result = await this.service.panierMystere({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        nom: true,
        prix: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PanierMystere })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePanierMystere(
    @common.Param() params: PanierMystereWhereUniqueInput,
    @common.Body() data: PanierMystereUpdateInput
  ): Promise<PanierMystere | null> {
    try {
      return await this.service.updatePanierMystere({
        where: params,
        data: {
          ...data,

          restaurant: data.restaurant
            ? {
                connect: data.restaurant,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          nom: true,
          prix: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PanierMystere })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePanierMystere(
    @common.Param() params: PanierMystereWhereUniqueInput
  ): Promise<PanierMystere | null> {
    try {
      return await this.service.deletePanierMystere({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          nom: true,
          prix: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/favorises")
  @ApiNestedQuery(FavorisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Favoris",
    action: "read",
    possession: "any",
  })
  async findFavorises(
    @common.Req() request: Request,
    @common.Param() params: PanierMystereWhereUniqueInput
  ): Promise<Favoris[]> {
    const query = plainToClass(FavorisFindManyArgs, request.query);
    const results = await this.service.findFavorises(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        panierMystere: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/favorises")
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "update",
    possession: "any",
  })
  async connectFavorises(
    @common.Param() params: PanierMystereWhereUniqueInput,
    @common.Body() body: FavorisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      favorises: {
        connect: body,
      },
    };
    await this.service.updatePanierMystere({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/favorises")
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "update",
    possession: "any",
  })
  async updateFavorises(
    @common.Param() params: PanierMystereWhereUniqueInput,
    @common.Body() body: FavorisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      favorises: {
        set: body,
      },
    };
    await this.service.updatePanierMystere({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/favorises")
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "update",
    possession: "any",
  })
  async disconnectFavorises(
    @common.Param() params: PanierMystereWhereUniqueInput,
    @common.Body() body: FavorisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      favorises: {
        disconnect: body,
      },
    };
    await this.service.updatePanierMystere({
      where: params,
      data,
      select: { id: true },
    });
  }
}
