/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PanierMystere } from "./PanierMystere";
import { PanierMystereCountArgs } from "./PanierMystereCountArgs";
import { PanierMystereFindManyArgs } from "./PanierMystereFindManyArgs";
import { PanierMystereFindUniqueArgs } from "./PanierMystereFindUniqueArgs";
import { CreatePanierMystereArgs } from "./CreatePanierMystereArgs";
import { UpdatePanierMystereArgs } from "./UpdatePanierMystereArgs";
import { DeletePanierMystereArgs } from "./DeletePanierMystereArgs";
import { FavorisFindManyArgs } from "../../favoris/base/FavorisFindManyArgs";
import { Favoris } from "../../favoris/base/Favoris";
import { Restaurant } from "../../restaurant/base/Restaurant";
import { PanierMystereService } from "../panierMystere.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PanierMystere)
export class PanierMystereResolverBase {
  constructor(
    protected readonly service: PanierMystereService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "read",
    possession: "any",
  })
  async _panierMysteresMeta(
    @graphql.Args() args: PanierMystereCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PanierMystere])
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "read",
    possession: "any",
  })
  async panierMysteres(
    @graphql.Args() args: PanierMystereFindManyArgs
  ): Promise<PanierMystere[]> {
    return this.service.panierMysteres(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PanierMystere, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "read",
    possession: "own",
  })
  async panierMystere(
    @graphql.Args() args: PanierMystereFindUniqueArgs
  ): Promise<PanierMystere | null> {
    const result = await this.service.panierMystere(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PanierMystere)
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "create",
    possession: "any",
  })
  async createPanierMystere(
    @graphql.Args() args: CreatePanierMystereArgs
  ): Promise<PanierMystere> {
    return await this.service.createPanierMystere({
      ...args,
      data: {
        ...args.data,

        restaurant: args.data.restaurant
          ? {
              connect: args.data.restaurant,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PanierMystere)
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "update",
    possession: "any",
  })
  async updatePanierMystere(
    @graphql.Args() args: UpdatePanierMystereArgs
  ): Promise<PanierMystere | null> {
    try {
      return await this.service.updatePanierMystere({
        ...args,
        data: {
          ...args.data,

          restaurant: args.data.restaurant
            ? {
                connect: args.data.restaurant,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PanierMystere)
  @nestAccessControl.UseRoles({
    resource: "PanierMystere",
    action: "delete",
    possession: "any",
  })
  async deletePanierMystere(
    @graphql.Args() args: DeletePanierMystereArgs
  ): Promise<PanierMystere | null> {
    try {
      return await this.service.deletePanierMystere(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Favoris], { name: "favorises" })
  @nestAccessControl.UseRoles({
    resource: "Favoris",
    action: "read",
    possession: "any",
  })
  async findFavorises(
    @graphql.Parent() parent: PanierMystere,
    @graphql.Args() args: FavorisFindManyArgs
  ): Promise<Favoris[]> {
    const results = await this.service.findFavorises(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Restaurant, {
    nullable: true,
    name: "restaurant",
  })
  @nestAccessControl.UseRoles({
    resource: "Restaurant",
    action: "read",
    possession: "any",
  })
  async getRestaurant(
    @graphql.Parent() parent: PanierMystere
  ): Promise<Restaurant | null> {
    const result = await this.service.getRestaurant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
