/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FavorisService } from "../favoris.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FavorisCreateInput } from "./FavorisCreateInput";
import { Favoris } from "./Favoris";
import { FavorisFindManyArgs } from "./FavorisFindManyArgs";
import { FavorisWhereUniqueInput } from "./FavorisWhereUniqueInput";
import { FavorisUpdateInput } from "./FavorisUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FavorisControllerBase {
  constructor(
    protected readonly service: FavorisService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Favoris })
  @nestAccessControl.UseRoles({
    resource: "Favoris",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFavoris(
    @common.Body() data: FavorisCreateInput
  ): Promise<Favoris> {
    return await this.service.createFavoris({
      data: {
        ...data,

        panierMystere: data.panierMystere
          ? {
              connect: data.panierMystere,
            }
          : undefined,

        utilisateur: data.utilisateur
          ? {
              connect: data.utilisateur,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        panierMystere: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Favoris] })
  @ApiNestedQuery(FavorisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Favoris",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async favorises(@common.Req() request: Request): Promise<Favoris[]> {
    const args = plainToClass(FavorisFindManyArgs, request.query);
    return this.service.favorises({
      ...args,
      select: {
        createdAt: true,
        id: true,

        panierMystere: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Favoris })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Favoris",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async favoris(
    @common.Param() params: FavorisWhereUniqueInput
  ): Promise<Favoris | null> {
    const result = await this.service.favoris({
      where: params,
      select: {
        createdAt: true,
        id: true,

        panierMystere: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Favoris })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Favoris",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFavoris(
    @common.Param() params: FavorisWhereUniqueInput,
    @common.Body() data: FavorisUpdateInput
  ): Promise<Favoris | null> {
    try {
      return await this.service.updateFavoris({
        where: params,
        data: {
          ...data,

          panierMystere: data.panierMystere
            ? {
                connect: data.panierMystere,
              }
            : undefined,

          utilisateur: data.utilisateur
            ? {
                connect: data.utilisateur,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          panierMystere: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          utilisateur: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Favoris })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Favoris",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFavoris(
    @common.Param() params: FavorisWhereUniqueInput
  ): Promise<Favoris | null> {
    try {
      return await this.service.deleteFavoris({
        where: params,
        select: {
          createdAt: true,
          id: true,

          panierMystere: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          utilisateur: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
